parried = false
around = false
depth = -1
image_speed = 1
alarm[0] = 1
image_alpha = 1
visible = true
alarm[3] = 6 * 60
hsp = 5
vsp = 5
dir = point_direction(x, y, obj_parent_player.x, obj_parent_player.y)